language: node_js
node_js:
- node
sudo: true
cache:
  yarn: true
branches:
  only:
  - master
env:
- CXX=g++-7
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
os:
- linux
before_install:
- openssl aes-256-cbc -K $encrypted_7bc5e0b36486_key -iv $encrypted_7bc5e0b36486_iv
  -in travis.enc -out ./travis -d
- wget https://github.com/Athenacle/athenacle.xyz/archive/master.zip
- unzip master.zip
- mv athenacle.xyz-master/* .
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt update
- sudo apt install libvips libvips-dev yarn
- git submodule update --init --recursive
- git clone https://github.com/Athenacle/posts.git
script:
- yarn
- yarn build
before_deploy:
- chmod 600 ./travis
deploy:
- provider: script
  skip_cleanup: true
  script: rsync --delete -Pav -e "ssh -o StrictHostKeyChecking=no -i ./travis  " ./public
    $deloy_user@$deploy_url:var/www/html/
  on:
    branch: master
